ALAUDA_OPERATOR2_TAG ?= OPENTELEMETRY-OPERATOR2-TAG-PLACEHOLDER
ALAUDA_COLLECTOR_TAG ?= OPENTELEMETRY-COLLECTOR-TAG-PLACEHOLDER
ALAUDA_JAEGER_TAG ?= JAEGER-TAG-PLACEHOLDER
ALAUDA_OAUTH2_PROXY_TAG ?= OAUTH2-PROXY-TAG-PLACEHOLDER

.PHONY: alauda-patch
alauda-patch:
	./hack/alauda-patch.sh "$(ALAUDA_OPERATOR2_TAG)" "$(ALAUDA_COLLECTOR_TAG)" "$(ALAUDA_JAEGER_TAG)" "$(ALAUDA_OAUTH2_PROXY_TAG)"